export const basePeluquerias = [
  {
    id: 1,
    nombre: 'Peluqueria Canina 1',
    direccion: 'Manuel Montt 23, Providencia, RM',
    telefono: '123456789',
    imagen: 'https://img.freepik.com/vector-premium/peluqueria-perros-gatos-simbolo-peluqueria-canina-simbolo-peluqueria-animales_662695-70.jpg?w=740',
    verificada: true,
    estrellas: 5,
  },
  {
    id: 2,
    nombre: 'Peluqueria Canina 2',
    direccion: 'Irarrázaval 123, Ñuñoa, RM',
    telefono: '123456789',
    imagen: 'https://img.freepik.com/vector-premium/peluqueria-perros-gatos-simbolo-peluqueria-canina-simbolo-peluqueria-animales_662695-70.jpg?w=740',
    verificada: false,
    estrellas: 4,
  },
  {
    id: 3,
    nombre: 'Peluqueria  Canina 3',
    direccion: 'Jose Pedro Alessandri 123, La Florida, RM',
    telefono: '123456789',
    imagen: 'https://img.freepik.com/vector-premium/peluqueria-perros-gatos-simbolo-peluqueria-canina-simbolo-peluqueria-animales_662695-70.jpg?w=740',
    verificada: false,
    estrellas: 3,
  },
  {
    id: 4,
    nombre: 'Peluqueria Canina 4',
    direccion: 'Gran Avenida 123, San Miguel, RM',
    telefono: '123456789',
    imagen: 'https://img.freepik.com/vector-premium/peluqueria-perros-gatos-simbolo-peluqueria-canina-simbolo-peluqueria-animales_662695-70.jpg?w=740',
    verificada: true,
    estrellas: 2,
  },
  {
    id: 5,
    nombre: 'Peluqueria Canina 5',
    direccion: 'Calle 5',
    telefono: '123456789',
    imagen: 'https://img.freepik.com/vector-premium/peluqueria-perros-gatos-simbolo-peluqueria-canina-simbolo-peluqueria-animales_662695-70.jpg?w=740',
    verificada: true,
    estrellas: 1,
  },
  {
    id: 6,
    nombre: 'Peluqueria Canina 6',
    direccion: 'Calle 6',
    telefono: '123456789',
    imagen: 'https://img.freepik.com/vector-premium/peluqueria-perros-gatos-simbolo-peluqueria-canina-simbolo-peluqueria-animales_662695-70.jpg?w=740',
    verificada: true,
    estrellas: 0,
  },
  {
    id: 7,
    nombre: 'Peluqueria Canina 7',
    direccion: 'Calle 7',
    telefono: '123456789',
    imagen: 'https://img.freepik.com/vector-premium/peluqueria-perros-gatos-simbolo-peluqueria-canina-simbolo-peluqueria-animales_662695-70.jpg?w=740',
    verificada: true,
    estrellas: 5,
  },
  {
    id: 8,
    nombre: 'Peluqueria Canina 8',
    direccion: 'Calle 8',
    telefono: '123456789',
    imagen: 'https://img.freepik.com/vector-premium/peluqueria-perros-gatos-simbolo-peluqueria-canina-simbolo-peluqueria-animales_662695-70.jpg?w=740',
    verificada: true,
    estrellas: 5,
  },
];
